proj-launch/config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :fluffys
  # map '/' to be a redirect to '/fluffy'
  root :to => redirect('/fluffys')
  get '/fluffys/:id/get_rewards', to: 'fluffys#get_rewards', as: 'get_rewards'
  get '/fluffys/:id/reset_rewards',  to: 'fluffys#reset_rewards', as: 'reset_rewards'
  get '/qrcode', to: 'foo#get_qrcode', as: 'get_qrcode'
  
  get '/qrcodescan', to: 'foo#redirecting_action', as: 'redirecting_action'
  
  get '/fluffys/recommend/:id/:password', to: 'fluffys#recommend', as: 'recommend'
  get '/fluffys/new',  to: 'fluffys#create', as: 'to_create'
  
  get 'fluffys/user/:id/:password', to: "fluffys#user", as: 'user'
  
  get 'fluffys/:id/login', to: "fluffys#login", as: 'to_login'
    
  get '/fluffys/pay/:id/:password/:budget', to: 'fluffys#pay', as: 'pay'
end

proj-launch/app/models/fluffys.rb
class Fluffys < ActiveRecord::Base
    def self.update_fluffy_coin(fluffy)
            if fluffy.fluffy_coin.to_f == 0
                fluffy.fluffy_coin = (fluffy.fluffy_coin.to_f + (100 * ((fluffy.budget.to_f - fluffy.remaining_budget.to_f)/fluffy.budget.to_f))).round(2)
                fluffy.save
            end
    end
    
    def self.reset_fluffy_coin(fluffy)
            if fluffy.fluffy_coin.to_f != 0
                fluffy.fluffy_coin = 0
                fluffy.save
            end
    end
    
    def self.run_recommendation
        #Returns all events that are recommended
        
        @events = Events.all
        @result = "bye"
        
        require 'pycall'
        require 'pycall/import'
        include PyCall::Import
        
        #Machine Learning model skeleton
#         pyfrom :sklearn
#         #Sample py code successfully runs!
# #         pyfrom :sklearn, import: :datasets
# #         pyfrom :sklearn, import: :svm
# #         pyfrom :'sklearn.model_selection', import: :train_test_split

#         model = LinearSVC()

#          X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(features, labels, df.index, test_size=0.33, random_state=0)
# model.fit(X_train, y_train)
#          y_pred = model.predict(X_test)
#         ############################Sort into categories and plot graph based on dataset

# #Remove null values
# df = df[pd.notnull(df['Event_name'])]
# df.info()
# print("done")


# #Use only necessary columns, i.e., 'Tag' and 'Event_name'
# col = ['Tag', 'Event_name']
# df = df[col]
# df.columns
# df.columns = ['Tag', 'Event_name']


# #Convert tags to Integer IDs
# df['category_id'] = df['Tag'].factorize()[0]

# #Sort the values according to tags
# from io import StringIO
# category_id_df = df[['Tag', 'category_id']].drop_duplicates().sort_values('category_id')
# print(category_id_df)

# #Store these tags in a dict
# category_to_id = dict(category_id_df.values)
# id_to_category = dict(category_id_df[['category_id', 'Tag']].values)
# print(id_to_category)
# print("done")

# #Plot the Graph of the density of each Data type
# import matplotlib.pyplot as plt
# fig = plt.figure(figsize=(8,6))
# df.groupby('Tag').Event_name.count().plot.bar(ylim=0)
# plt.show()

# #Sort the 'Event_name's according to their term frequency and take log of it(tfidf)
# from sklearn.feature_extraction.text import TfidfVectorizer
# tfidf = TfidfVectorizer(sublinear_tf=True, min_df=1, norm='l2', encoding='utf-8', ngram_range=(1, 2), stop_words='english')
# features = tfidf.fit_transform(df.Event_name).toarray()
# labels = df.category_id
# features.shape

# #######################################Generate uni and bigrams

# from sklearn.feature_selection import chi2
# import numpy as np

# #To check correlatio between two terms
# N = 2
# for Tag, category_id in sorted(category_to_id.items()):
#   features_chi2 = chi2(features, labels == category_id)
#   indices = np.argsort(features_chi2[0])
#   feature_names = np.array(tfidf.get_feature_names())[indices]
#   #Define unigrams and bigrams
#   unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
#   bigrams = [v for v in feature_names if len(v.split(' ')) == 2]

#   print("# '{}':".format(Tag))
#   print("  . Most correlated unigrams:\n       . {}".format('\n       . '.join(unigrams[-N:])))
#   print("  . Most correlated bigrams:\n       . {}".format('\n       . '.join(bigrams[-N:])))

# #############################################Initial wrong prediction

# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.feature_extraction.text import TfidfTransformer
# from sklearn.naive_bayes import MultinomialNB

# X_train, X_test, y_train, y_test = train_test_split(df['Event_name'], df['Tag'],train_size=0.7)

# #Convert into matrix
# count_vect = CountVectorizer()
# X_train_counts = count_vect.fit_transform(X_train)
# tfidf_transformer = TfidfTransformer()
# X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
# print(X_train_tfidf)

# clf = MultinomialNB().fit(X_train_tfidf, y_train)



# print(clf.predict(count_vect.transform([ref.child("Sentence").get()])))



# #####################################################Compare the ML models' accuracies
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.svm import LinearSVC

# from sklearn.model_selection import cross_val_score


# models = [
#     RandomForestClassifier(n_estimators=200, max_depth=3, random_state=0),
#     LinearSVC(),
#     MultinomialNB(),
#     LogisticRegression(random_state=0),
# ]
# CV = 5
# cv_df = pd.DataFrame(index=range(CV * len(models)))
# entries = []

# for model in models:
#   model_name = model.__class__.__name__
#   accuracies = cross_val_score(model, features, labels, scoring='accuracy', cv=CV)
#   for fold_idx, accuracy in enumerate(accuracies):
#     entries.append((model_name, fold_idx, accuracy))
# cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])
# print(cv_df)

# ###################################################Plot the models' accuracy graph
# import seaborn as sns

# sns.boxplot(x='model_name', y='accuracy', data=cv_df)
# sns.stripplot(x='model_name', y='accuracy', data=cv_df,
#               size=8, jitter=True, edgecolor="gray", linewidth=2)
# plt.show()

# cv_df.groupby('model_name').accuracy.mean()
# ###################################################Predict on test and train

# from sklearn.model_selection import train_test_split

# model = LinearSVC()

# X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(features, labels, df.index, test_size=0.33, random_state=0)
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)

# ####################################################Confusion matrix based on LinearSVC

# from sklearn.metrics import confusion_matrix


# conf_mat = confusion_matrix(y_test, y_pred)
# fig, ax = plt.subplots(figsize=(8,6))
# sns.heatmap(conf_mat, annot=True, fmt='d',
#             xticklabels=category_id_df.Tag.values, yticklabels=category_id_df.Tag.values)
# plt.ylabel('Actual')
# plt.xlabel('Predicted')
# plt.show()

# ###################################################Correct the wrongly predicted values and print it
# from IPython.display import display

# for predicted in category_id_df.category_id:
#   for actual in category_id_df.category_id:
#     if predicted != actual and conf_mat[actual, predicted] >= 6:
#       print("'{}' predicted as '{}' : {} examples.".format(id_to_category[actual], id_to_category[predicted], conf_mat[actual, predicted]))
#       display(df.loc[indices_test[(y_test == actual) & (y_pred == predicted)]][['Tag', 'Event_name']])
#       print('')

# ##################################################

# model.fit(features, labels)

# #################################################Correctly generated uni and bigrams
# from sklearn.feature_selection import chi2

# N = 2
# for Product, category_id in sorted(category_to_id.items()):
#   indices = np.argsort(model.coef_[category_id])
#   feature_names = np.array(tfidf.get_feature_names())[indices]
#   unigrams = [v for v in reversed(feature_names) if len(v.split(' ')) == 1][:N]
#   bigrams = [v for v in reversed(feature_names) if len(v.split(' ')) == 2][:N]
#   print("# '{}':".format(Product))
#   print("  . Top unigrams:\n       . {}".format('\n       . '.join(unigrams)))
#   print("  . Top bigrams:\n       . {}".format('\n       . '.join(bigrams)))

#   ################################################Corrected prediction with updation on firebase


#   texts = [ref.child("Sentence").get()]
# text_features = tfidf.transform(texts)
# predictions = model.predict(text_features)

# switcher = {
#          "Cultural":0,
#          "Sports":1,
#          "Coding":2,
#         "Business":3,
#     }



# for text, predicted in zip(texts, predictions):
#   print('"{}"'.format(text))
#   print("  - Predicted as: '{}'".format(id_to_category[predicted]))
#   print(switcher[id_to_category[predicted]])
#   ref.update({'value':switcher[id_to_category[predicted]]})

# ##########################################



#   from sklearn import metrics
# print(metrics.classification_report(y_test, y_pred,
#                                     target_names=df['Tag'].unique()))
# end = time. time()
# print(str(end - start)+" seconds to complete!")

        status = "success"
        
        @result = status
#         print(@result)
        
        #Using dummy variables to illustrate output from ML model
        #TODO: Remove interests from Database events
        interests = ["Sports", "Reading"]
        name_list = ['Basketball Tournament', 'Book club']
        @events = Events.where(name: name_list)
        #@events = Events.all
        return @events, @result
    end
    
    def self.is_outofRange id
        if id > Fluffys.count
            return true
        else
            return false
        end
    end
    
    def self.merge_parm fluffy_params
        @new_params = fluffy_params.merge!(:fluffy_coin => '0')
        return @new_params
    end
    
    def self.is_too_small id
        if id < 1
            return true
        else
            return false
        end
    end
    
end

proj-launch/app/controllers/fluffys_controller.rb
class FluffysController < ApplicationController

  def show
    print 123
    id = params[:id] # retrieve movie ID from URI route
    @fluffy = Fluffys.find(id) # look up movie by unique ID
    @events = Events.find(id)
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @fluffy = Fluffys.all
    @events = Events.all
  end

  def new
    # default: render 'new' template
  end
  
  def recommend
    id = params[:id]
    password = params[:password]
    @result = "bye"
    @events = Events.all
    @budget = @events[0].budget
    @events, @result = Fluffys.run_recommendation
    #redirect_to recommend_path
    # default: render 'recommend' template
    if params[:commit] == "Recommend to login"
        redirect_to user_path(params[:id], params[:password])
    end
  end

  def create
    #@new_fluffy = Fluffys.new(:name => movie_params.name, :budget => movie_params.budget, :remaining_budget => movie_params.remaining_budget, :fluffy_coin => '0')
    print("params")
    print(params)
    if params[:commit] == "Save Changes"
        #new_params = fluffy_params.merge!(:fluffy_coin => '0')
        new_params = Fluffys.merge_parm(fluffy_params)
        @fluffy = Fluffys.create!(new_params)
        print("new_params")
        print(new_params)
        flash[:notice] = "#{@fluffy.name} was successfully created. \n Your id is: #{@fluffy.id}"
        redirect_to fluffys_path
    elsif params[:commit] == "Login"
        print("fluffy_params.id + fluffy_params.password: ")
        print(fluffy_params)
        redirect_to user_path(fluffy_params[:id], fluffy_params[:password])
    end
  end
    
  def login
    
  end
    
  def login_submit
      
  end
  
  def pay
      @fluffy = Fluffys.find params[:id]
      remaining_budget = @fluffy.remaining_budget.to_i
      fluffy_coin = @fluffy.fluffy_coin.to_i
      budget = params[:budget].to_i
      @fluffy.remaining_budget = remaining_budget + fluffy_coin - budget
      @fluffy.fluffy_coin = budget * 0.05
      @fluffy.save
      redirect_to user_path(params[:id], params[:password])
  end
    
  def edit
    @fluffy = Fluffys.find params[:id]
  end

  def update
    @fluffy = Fluffys.find params[:id]
    @fluffy.update_attributes!(movie_params)
    flash[:notice] = "#{@fluffy.name} was successfully updated."
    redirect_to fluffys_path(@fluffy)
  end

  def destroy
    @fluffy = Fluffys.find(params[:id])
    @fluffy.destroy
    flash[:notice] = "Movie '#{@fluffy.name}' deleted."
    redirect_to fluffys_path
  end
  
  def get_rewards
      #@fluffy = Fluffys.all
      #Fluffys.update_fluffy_coin
      #redirect_to fluffys_path
      @fluffy = Fluffys.find(params[:id])
      Fluffys.update_fluffy_coin(@fluffy)
      redirect_to user_path(params[:id], @fluffy.password)
  end
  
  def user
      id = Integer(params[:id])
      @events = Events.all
      if Fluffys.is_outofRange(id)
          flash[:notice] = "User ID Does not exsit"
          redirect_to fluffys_path
      elsif Fluffys.is_too_small(id)
          flash[:notice] = "User ID can not be smaller than 1"
          redirect_to fluffys_path
      else
          @fluffy = Fluffys.find params[:id]
          if @fluffy.password != params[:password]
              flash[:notice] = "User ID: #{@fluffy.id} authentification failed"
              #flash[:notice] = "Password is #{@fluffy.password}} "
              redirect_to fluffys_path
          end
      end
  end

  def reset_rewards
      #Fluffys.reset_fluffy_coin
      #redirect_to fluffys_path
      @fluffy = Fluffys.find(params[:id])
      Fluffys.reset_fluffy_coin(@fluffy)
      redirect_to user_path(params[:id], @fluffy.password)
  end
    
#   def get_recommend
#       @events = Events.all
#       #Fluffys.update_fluffy_coin
#       Fluffys.run_recommendation
#       redirect_to get_recommend_path
#   end

  
  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def fluffy_params
    params.require(:fluffy).permit(:name, :budget, :remaining_budget, :fluffy_coin, :password, :id)
  end
end

proj-launch/app/views/fluffys/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@fluffy), :method => :put do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, 'title', :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Update Movie Info', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

proj-launch/app/views/fluffys/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->

<%= link_to 'Sign Up', to_create_path, :class => 'btn btn-primary' %>
<%= link_to 'Login', to_login_path(1), :class => 'btn btn-primary' %>

proj-launch/app/views/fluffys/login.html.erb
<div class = "d-flex align-items-center justify-content-center">
    <h2>Login</h2>
</div>
    
<div>
<%= form_tag fluffys_path, :class => 'form' do %>
  <%= label :fluffy, :id, 'ID', :class => 'col-form-label' %>
  <%= number_field :fluffy, :id, :class => 'form-control', required: true %>
  <%= label :fluffy, :password, 'Password', :class => 'col-form-label' %>
  <%= text_field :fluffy, :password, :class => 'form-control', required: true %>

  <br/>
  <%= submit_tag 'Login', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', fluffys_path, :class => 'btn btn-secondary' %>
<% end %>
    
<div class = "d-flex align-items-center justify-content-center">
    <h2>Not Having an account? Start Saving Today!</h2>
    <br>
</div>
    <%= link_to 'Sign Up', to_create_path, :class => 'btn btn-primary' %>

</div>

proj-launch/app/views/fluffys/new.html.erb
<h2>Create New Fluffy</h2>

<%= form_tag fluffys_path, :class => 'form' do %>
  <%= label :fluffy, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :fluffy, :name, :class => 'form-control', required: true %>
  <%= label :fluffy, :budget, 'Budget', :class => 'col-form-label' %>
  <%= number_field :fluffy, :budget, :class => 'form-control', step: 0.01, required: true %>
  <%= label :fluffy, :remaining_budget, 'Remaining budget', :class => 'col-form-label' %>
  <%= number_field :fluffy, :remaining_budget, :class => 'form-control', step: 0.01, required: true %>

  <%= label :fluffy, :password, 'Password', :class => 'col-form-label' %>
  <%= text_field :fluffy, :password, :class => 'form-control', required: true %>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', fluffys_path, :class => 'btn btn-secondary' %>
<% end %>

proj-launch/app/views/fluffys/qr.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>QR Code Scanning</h2>

<ul id="qr">
  <li>
       Please Scan the QR Code in front of you 
  </li>
 
</ul>

proj-launch/app/views/fluffys/recommend.html.erb
<h2>Recommended events</h2>

<div class="card" style="width: 18rem;">
  <img src= "https://i.guim.co.uk/img/media/77e3e93d6571da3a5d77f74be57e618d5d930430/0_0_2560_1536/master/2560.jpg?width=965&quality=45&auto=format&fit=max&dpr=2&s=18f648aedca5c5e6f7814cd43429fd2b" class="card-img-top" alt="Book club">
  <div class="card-body">
    <h5 class="card-title">Book club</h5>
    <p class="card-text">Library</p>

    <%= link_to 'Home', '/fluffys', :class => 'btn btn-primary' %>
  </div>
</div>

<br><br>
<h5><%= @result %></h5>
<%= link_to 'Pay', pay_path(params[:id], params[:password], @budget), :class => 'btn btn-secondary' %>
<%= link_to 'Back to user page', user_path(params[:id], params[:password]), :class => 'btn btn-secondary' %>
<%= link_to 'Return to home', fluffys_path, :class => 'btn btn-secondary' %>

proj-launch/app/views/fluffys/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>Details about <em><%= @fluffy.title %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%= @fluffy.rating %>
  </li>
  <li>
    Released on:
    <%= @fluffy.release_date.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @fluffy.description %>
</p>

<div class="row">
  <%= link_to 'Edit', edit_movie_path(@fluffy), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@fluffy), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, :class => 'btn btn-primary col-2' %>
</div>

proj-launch/app/views/fluffys/user.html.erb
<!--  This file is app/views/movies/index.html.erb -->

<h2>Student info</h2>
<div class="card" style="width: 18rem;">
  <img src= "https://fashionista.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTc5ODMxNjUxNTgzNDAzNjMx/emma-watson-ralph-lauren-white-dress-noah-premiere-3.jpg" class="card-img-top" alt="No Img Yet">
  <div class="card-body">
    <h5 class="card-title">Emma Waston</h5>
    <p class="card-text">have saved $20000 with Fluffy since 2021</p>

    <%= link_to 'Home', '/fluffys', :class => 'btn btn-primary' %>
  </div>
</div>





<%#  Part 2: Start here... %>
<br>
<br>
<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Budget</th>
      <th>Remaining Budget</th>
      <th>Fluffy Coins</th>
      <th>Password</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
          <%= @fluffy.id %>
        </td>
        <td>
          <%= @fluffy.name %>
        </td>
        <td>
          <%= @fluffy.budget %>
        </td>
        <td>
          <%= @fluffy.remaining_budget %>
        </td>
        <td>
            <%= @fluffy.fluffy_coin %>
        </td>
        <td>
            <%= @fluffy.password %>
        </td>
      </tr>
  </tbody>
</table>

<%= link_to 'Get Rewards', get_rewards_path(@fluffy.id), :class => 'btn btn-primary' %>
<%= link_to 'Reset Rewards', reset_rewards_path(@fluffy.id), :class => 'btn btn-primary' %>

<br><br><br><br>

<h2 class = "text-info">Available events</h2>

<table class="table table-striped col-md-12" id="events">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Interests</th>
      <th>Budget</th>
      <th>Frequency of entertainment</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |movie| %>
      <tr>
        <td>
            <a href="#" class="stretched-link text-primary" style="position: relative;"><%= movie.name %></a>
        </td>
        <td>
          <%= movie.location %>
        </td>
        <td>
            <span class="badge badge-pill badge-info"><%= movie.interests %></span>
        </td>
        <td>
            <%= movie.budget %>
        </td>
        <td>
            <%= movie.frequency_of_entertainment %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<style type=”text/css”>
     .th{
          color:red;
     }
</style>

<%= link_to 'Recommend events', recommend_path(@fluffy.id, @fluffy.password), :class => 'btn btn-primary' %>